# Copyright (C) 2020 Reactive Markets Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
version: "3"
services:
  schema:
    container_name: schema
    image: registry.gitlab.com/reactivemarkets/private-registry/schema:${REACTIVE_TAG}
    volumes:
      - sqlite-data:/schema/sqlite/db

  matchlob:
    container_name: matchlob
    image: registry.gitlab.com/reactivemarkets/private-registry/reactive-cpp:${REACTIVE_TAG}
    entrypoint: /cpp/bin/re-matchlob
    command: -f matchlob.conf
    environment:
      REACTIVE_PATH: /cpp/etc
    ipc: host
    networks:
      - reactive-net
    ports:
      - 8277:8277
    restart: on-failure
    volumes:
      - ./etc:/cpp/etc:ro
      - sqlite-data:/data/db

  matchfix:
    container_name: matchfix
    image: registry.gitlab.com/reactivemarkets/private-registry/reactive-cpp:${REACTIVE_TAG}
    entrypoint: /cpp/bin/re-matchfix
    command: -f matchfix.conf
    environment:
      REACTIVE_PATH: /cpp/etc
    ipc: host
    networks:
      - reactive-net
    restart: on-failure
    volumes:
      - ./etc:/cpp/etc:ro
      - sqlite-data:/data/db

networks:
  reactive-net:

volumes:
  sqlite-data:
