# Copyright (C) 2020 Reactive Markets Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
version: "3.5"
services:
  schema:
    container_name: crossfire-schema
    image: registry.gitlab.com/reactivemarkets/private-registry/schema:${REACTIVE_TAG}
    volumes:
      - mysql-init:/schema/mariadb:ro

  mariadb:
    container_name: crossfire-mariadb
    image: mariadb:latest
    depends_on:
      - schema
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_INITDB_SKIP_TZINFO: 1
      REACTIVE_SQL_PASS: test
    networks:
      - crossfire-net
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-init:/docker-entrypoint-initdb.d:ro

  redis:
    container_name: crossfire-redis
    image: redis:5-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - crossfire-net
    restart: on-failure
    volumes:
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf:ro

  refdata:
    container_name: crossfire-refdata
    image: registry.gitlab.com/reactivemarkets/private-registry/reactive-go:${REACTIVE_TAG}
    command: refdata
    depends_on:
      - mariadb
      - redis
    environment:
      REACTIVE_SQL_TYPE: mysql
      REACTIVE_SQL_HOST: mariadb
      REACTIVE_SQL_USER: reactiveuser
      REACTIVE_SQL_PASS: test
      REACTIVE_SQL_NAME: uatdb
      REACTIVE_SQL_PORT: 3306
      REACTIVE_REDIS_HOST: redis
      REACTIVE_REDIS_PORT: 6379
    networks:
      - crossfire-net
    restart: on-failure

  revalrates:
    container_name: crossfire-revalrates
    image: registry.gitlab.com/reactivemarkets/private-registry/reactive-go:${REACTIVE_TAG}
    command: revalrates
    depends_on:
      - refdata
    environment:
      REACTIVE_REDIS_HOST: redis
      REACTIVE_REDIS_PORT: 6379
    networks:
      - crossfire-net
    restart: on-failure

  takerfix:
    container_name: crossfire-takerfix
    image: registry.gitlab.com/reactivemarkets/private-registry/reactive-cpp:${REACTIVE_TAG}
    entrypoint: /cpp/bin/re-takerfix
    command: -f takerfix.conf
    depends_on:
      - mariadb
    environment:
      REACTIVE_PATH: /cpp/etc
      REACTIVE_SQL_TYPE: mysql
      REACTIVE_SQL_HOST: mariadb
      REACTIVE_SQL_USER: reactiveuser
      REACTIVE_SQL_PASS: test
      REACTIVE_SQL_NAME: uatdb
      REACTIVE_SQL_PORT: 3306
    ipc: host
    networks:
      - crossfire-net
    ports:
      - 8285:8285
    restart: on-failure
    volumes:
      - ./etc:/cpp/etc:ro

  clientpricer:
    container_name: crossfire-clientpricer
    image: registry.gitlab.com/reactivemarkets/private-registry/reactive-go:${REACTIVE_TAG}
    command: clientpricer --config=clientpricer.conf
    depends_on:
      - revalrates
    environment:
      REACTIVE_PATH: /go/etc
      REACTIVE_REDIS_HOST: redis
      REACTIVE_REDIS_PORT: 6379
    ipc: host
    networks:
      - crossfire-net
    restart: on-failure
    volumes:
      - ./etc:/go/etc:ro

networks:
  crossfire-net:
    name: crossfire-net

volumes:
  mysql-data:
    name: crossfire-mysql-data
  mysql-init:
    name: crossfire-mysql-init
